[package]
name = "md-tool"
version = "1.1.0"
authors = ["Jsi1v4 <git@jsi1v4.com>"]
edition = "2018"

[alias]
start = "run"
start-prod = "run --release"
build = "build"
build-prod = "build --release"

[dependencies]
regex = "1"
